add basic puppet/yaml checks

diff --git a/hooks/pre-receive-new b/hooks/pre-receive-new
--- a/hooks/pre-receive-new
+++ b/hooks/pre-receive-new
@@ -56,19 +56,58 @@ validate_ref() {
                         case $extension in
                             pp)
                                 echo "Testing puppet syntax on $file ..."
+                                # Remove import lines while parsing
+                                # http://projects.puppetlabs.com/issues/9670#note-14
+                                sed -i -e '/^import / d' $to_check >/dev/null 2>&1
+                                # Puppet syntax check
+                                puppet parser validate $to_check >/dev/null 2>&1
+                                if [ $? -ne 0 ]; then
+                                    echo "Puppet syntax error in ${file}. Run 'puppet parser validate ${file}'" >&2
+                                    STATUS=2
+                                fi
+
                                 echo "Testing puppet linting style on $file ..."
+                                # puppet-lint check
+                                puppet-lint $PUPPETLINT_FLAGS --log-format "${file}:%{linenumber} %{KIND} - %{message}" $to_check 2> /dev/null
+                                if [ $? -ne 0 ]; then
+                                    STATUS=2
+                                fi
                                 ;;
 
                             erb)
                                 echo "Testing erb syntax on $file ..."
+                                # syntax check templates - this doesn't catch a lot of mistakes,
+                                # but it should catch gross mistakes
+                                # the sed is a workaround for fixing lines beginning with %
+                                # as -P argument is not given to erb - still checks the line
+                                #
+                                # Example: sudoers file generated by an erb template,
+                                #          which has entry based on the group membership
+                                sed -i 's/^%/<%= "%" %>/' "${to_check}"
+                                erb -x -T - "${to_check}" | ruby -c >/dev/null 2>&1
+                                if [ $? -ne 0 ]; then
+                                    echo "ERB syntax error in ${file}" >&2
+                                    STATUS=2
+                                fi
                                 ;;
 
                             yml|yaml)
                                 echo "Testing yaml syntax on $file ..."
+                                # syntax YAML files, https://ttboj.wordpress.com/2013/08/25/finding-yaml-errors-in-puppet/
+                                ruby -ryaml -e "YAML.parse(File.open('${to_check}'))" >/dev/null 2>&1
+                                if [ $? -ne 0 ]; then
+                                    echo "YAML syntax error in ${file}" >&2
+                                    STATUS=2
+                                fi
                                 ;;
 
                             json)
                                 echo "Testing json syntax on $file ..."
+                                ruby -rjson -e "JSON.parse(File.open('${to_check}').read)" >/dev/null 2>&1
+                                if [ $? -ne 0 ]; then
+                                    echo "JSON syntax error in ${file}" >&2
+                                    STATUS=2
+                                fi
                                 ;;
                         esac
                     fi
